[tool.black]
line-length = 88
target-version = ['py39']

[tool.mypy]
python_version = '3.9'
ignore_missing_imports = true
strict = true
show_error_codes = true
warn_unused_configs = true
exclude = ['node_modules']

[build-system]
requires = ['setuptools', 'wheel']
